name: Latest blog post workflow
on:
  pull_request:
  push:
    branches:
      - main
  
  schedule:
    # Runs every hour, on the hour.
    - cron: "0 2 * * 1-5"
    
  # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update with latest blog post
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get RSS Feed
        uses: kohrongying/readme-the-rss@master
        with:
          feed_url: https://zamaan.hashnode.dev/rss.xml
          count: 6
      - name: Commit and push
        uses: EndBug/add-and-commit@v4
        with:
          author_name: RootProgrammer
          author_email: zamaan.md19@gmail.com
          message: 'Update README'
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_GITHUB_TOKEN }}
