name: Latest blog post workflow

on:
  pull_request: {}
  push:
    branches:
      - main
  schedule:
    # Runs every Monday to Friday, at 02:00.
    - cron: '0 2 * * 1-5'
  workflow_dispatch: {}

jobs:
  update-readme-with-blog:
    name: Update with latest blog post
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get RSS Feed
        uses: gautamkrishnar/blog-post-workflow@master
        with: 
          max_post_count: "19"
          feed_list: "https://dev.to/feed/root_programmer.rss, https://medium.com/feed/@root_programmer, https://zamaan.hashnode.dev/rss.xml"

      - name: Commit and push
        uses: EndBug/add-and-commit@v4
        with:
          author_name: RootProgrammer
          author_email: zamaan.md19@gmail.com
          message: 'Update README'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
